spring:
  profiles:
    active: local
  thymeleaf.cache: false
  datasource.url: jdbc:h2:mem:testdb
---
spring:
  profiles: local
  thymeleaf.cache: false
logging:
  level:
    root: INFO
---
spring:
  profiles: prod
  thymeleaf.cache: true
logging:
  level:
    root: WARN