spring:
  profiles:
    active: local
  thymeleaf.cache: false
  datasource:
    url: jdbc:h2:mem:testdb
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: local
  thymeleaf.cache: false
  datasource:
    url: jdbc:h2:mem:testdb
#  redis:
#    host: localhost
#    port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf.cache: true
logging:
  level:
    root: WARN